// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ProjectResponse {
    "status": number;
    "statusText": string;
    "contentType": string;
    "body": string;

    /** Creates a new ProjectResponse instance. */
    constructor($$source: Partial<ProjectResponse> = {}) {
        if (!("status" in $$source)) {
            this["status"] = 0;
        }
        if (!("statusText" in $$source)) {
            this["statusText"] = "";
        }
        if (!("contentType" in $$source)) {
            this["contentType"] = "";
        }
        if (!("body" in $$source)) {
            this["body"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): ProjectResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProjectResponse($$parsedSource as Partial<ProjectResponse>);
    }
}
