// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * MenuItemPayload is the wire-format for a single native menu item, built
 * frontend-side from a registered Action.
 */
export class MenuItemPayload {
    "path": string;
    "actionId": string;
    "label": string;
    "group": string;
    "order": number;
    "accelerator": string;
    "enabled": boolean;

    /** Creates a new MenuItemPayload instance. */
    constructor($$source: Partial<MenuItemPayload> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("actionId" in $$source)) {
            this["actionId"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("group" in $$source)) {
            this["group"] = "";
        }
        if (!("order" in $$source)) {
            this["order"] = 0;
        }
        if (!("accelerator" in $$source)) {
            this["accelerator"] = "";
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MenuItemPayload instance from a string or object.
     */
    static createFrom($$source: any = {}): MenuItemPayload {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MenuItemPayload($$parsedSource as Partial<MenuItemPayload>);
    }
}

/**
 * SetItemsPayload wraps a list of items for the MenuSetItemsEvent.
 */
export class SetItemsPayload {
    "items": MenuItemPayload[];

    /** Creates a new SetItemsPayload instance. */
    constructor($$source: Partial<SetItemsPayload> = {}) {
        if (!("items" in $$source)) {
            this["items"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SetItemsPayload instance from a string or object.
     */
    static createFrom($$source: any = {}): SetItemsPayload {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField0_0($$parsedSource["items"]);
        }
        return new SetItemsPayload($$parsedSource as Partial<SetItemsPayload>);
    }
}

// Private type creation functions
const $$createType0 = MenuItemPayload.createFrom;
const $$createType1 = $Create.Array($$createType0);
