// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ProjectService bridges HTTP calls from the frontend through Go to the
 * project API server. Used to work around a WKWebView bug where fetch (and
 * allegedly XHR) drops the body of PUT/DELETE/PATCH requests; the Go HTTP
 * stack has no such issue. Routing through here also gives us a hook for
 * mirroring file updates to the local disk so external editors (e.g. Aseprite
 * for textures) can pick them up.
 * 
 * The bridge uses string for body fields. Go strings hold arbitrary byte
 * sequences, but they have to traverse JSON to/from the frontend. That's fine
 * for text uploads (the only case we have today). Binary upload/download will
 * need a base64 (or chunked) variant.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Request performs an HTTP request from Go and returns the response. The
 * frontend uses this for PUT/DELETE/PATCH to bypass the WKWebView body-drop
 * bug. `path` is the request path including any prefix (e.g.
 * "/v1/projects/demo/files/foo.txt"). `contentType` may be empty for methods
 * without a body. `body` may be "" for DELETE.
 */
export function Request(method: string, path: string, contentType: string, body: string): $CancellablePromise<$models.ProjectResponse> {
    return $Call.ByID(282864377, method, path, contentType, body).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.ProjectResponse.createFrom;
